# Azure Pipelines CI job template for PyDM Tests

parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        python.name: '3_6'
      Python37:
        python.version: '3.7.3'
        python.name: '3_7'
  continueOnError: true
  dependsOn:
    - Build

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: 'Windows - Add conda to PATH'
    condition: eq(variables['agent.os'], 'Windows_NT' )

  - bash: |
      conda config --set always_yes yes
      conda config --set channel_priority strict
      conda config --set show_channel_urls yes
      conda config --add channels conda-forge
    displayName: 'Anaconda - Configure'

  - script: |
      echo Python Version $(python.version)
      conda create --yes --quiet --name test-environment-$(python.name) python=$(python.version)
    displayName: 'Anaconda - Create'

  - bash: |
      conda config --add channels 'file:///$(Build.Repository.LocalPath)/anaconda_package'
    displayName: 'Anaconda - Configure - Add local bld-dir'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'anaconda_package'
      downloadPath: $(Build.Repository.LocalPath)/
    displayName: Artifact Download - Anaconda Packages

  - script: |
      call activate test-environment-$(python.name)
      conda install python=$(python.version) pytest-azurepipelines pydm --file dev-requirements.txt --update-deps
    displayName: 'Anaconda - Install Dependencies'

  - script: |
      call activate test-environment-$(python.name)
      conda info
      conda list
      python -c "from PyQt5 import QtCore; print(QtCore)"
    displayName: 'Debug - Conda List'
    continueOnError: false

  - script: |
      call activate test-environment-$(python.name)
      python run_tests.py --timeout 30 --show-cov --test-run-title="Tests for $(Agent.OS) - Python $(python.version)" --napoleon-docstrings
    displayName: 'Tests - Run'
    continueOnError: false

  - script: |
      call activate test-environment-$(python.name)
      codecov
    displayName: 'Codecov - Upload'
    continueOnError: true
